version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    reviewers:
      - Emilien-Foissotte
    groups:
      python-packages:
        patterns:
          - "*"
