repos:
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.7.0-4
  hooks:
    - id: shfmt         # prebuilt upstream executable
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Use the ref you want to point at
  hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: detect-aws-credentials
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    # -   id: no-commit-to-branch  # ensure that no-commit reaches other branches than fix/xxxx or feat/xxx
    #     args: ['--pattern', '^(?!((main|fix|feat)\/[a-zA-Z0-9\-_]+)$).*']
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.0.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
