# .github/workflows/streamlit-app.yml
name: Unit Testing Streamlit app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: python
      - name: Install uv package manager
        run: pip install uv
      - name: Install dependencies from lock file
        run: |
          export UV_PROJECT_ENVIRONMENT=$Python3_ROOT_DIR
          uv sync
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: home.py
          ruff: true
          skip-smoke: true
          # Add pytest-args to output junit xml
          pytest-args: -v --junit-xml=test-results.xml
      - if: always()
        uses: pmeier/pytest-results-action@v0.7.1
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
